/* AUTO-GENERATED by scripts/generate-content-media.cjs. Do not edit manually. */

export type ProductSizeKey = 'S' | 'M' | 'L';

export interface GeneratedProductMedia {
  title: string;
  folder: string;
  sizes: Record<ProductSizeKey, string[]>;
}

export const generatedProductMedia: Record<string, GeneratedProductMedia> = {
  "rose-001": {
    "title": "Аваланж Белая",
    "folder": "Аваланж Белая",
    "sizes": {
      "S": [
        "/products/roses/rose-001/sizes/S/1.webp",
        "/products/roses/rose-001/sizes/S/2.webp",
        "/products/roses/rose-001/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-001/sizes/M/1.webp",
        "/products/roses/rose-001/sizes/M/2.webp",
        "/products/roses/rose-001/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-001/sizes/L/1.webp",
        "/products/roses/rose-001/sizes/L/2.webp",
        "/products/roses/rose-001/sizes/L/3.webp"
      ]
    }
  },
  "rose-002": {
    "title": "Аква",
    "folder": "Аква",
    "sizes": {
      "S": [
        "/products/roses/rose-002/sizes/S/1.webp",
        "/products/roses/rose-002/sizes/S/2.webp",
        "/products/roses/rose-002/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-002/sizes/M/1.webp",
        "/products/roses/rose-002/sizes/M/2.webp",
        "/products/roses/rose-002/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-002/sizes/L/1.webp",
        "/products/roses/rose-002/sizes/L/2.webp",
        "/products/roses/rose-002/sizes/L/3.webp"
      ]
    }
  },
  "rose-003": {
    "title": "Барбодос",
    "folder": "Барбодос",
    "sizes": {
      "S": [
        "/products/roses/rose-003/sizes/S/1.webp",
        "/products/roses/rose-003/sizes/S/2.webp",
        "/products/roses/rose-003/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-003/sizes/M/1.webp",
        "/products/roses/rose-003/sizes/M/2.webp",
        "/products/roses/rose-003/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-003/sizes/L/1.webp",
        "/products/roses/rose-003/sizes/L/2.webp",
        "/products/roses/rose-003/sizes/L/3.webp"
      ]
    }
  },
  "rose-004": {
    "title": "Баттеркап",
    "folder": "Баттеркап",
    "sizes": {
      "S": [
        "/products/roses/rose-004/sizes/S/1.webp",
        "/products/roses/rose-004/sizes/S/2.webp",
        "/products/roses/rose-004/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-004/sizes/M/1.webp",
        "/products/roses/rose-004/sizes/M/2.webp",
        "/products/roses/rose-004/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-004/sizes/L/1.webp",
        "/products/roses/rose-004/sizes/L/2.webp",
        "/products/roses/rose-004/sizes/L/3.webp"
      ]
    }
  },
  "rose-005": {
    "title": "Вайт Барбодос",
    "folder": "Вайт Барбодос",
    "sizes": {
      "S": [
        "/products/roses/rose-005/sizes/S/1.webp",
        "/products/roses/rose-005/sizes/S/2.webp",
        "/products/roses/rose-005/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-005/sizes/M/1.webp",
        "/products/roses/rose-005/sizes/M/2.webp",
        "/products/roses/rose-005/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-005/sizes/L/1.webp",
        "/products/roses/rose-005/sizes/L/2.webp",
        "/products/roses/rose-005/sizes/L/3.webp"
      ]
    }
  },
  "rose-006": {
    "title": "Вау",
    "folder": "Вау",
    "sizes": {
      "S": [
        "/products/roses/rose-006/sizes/S/1.webp",
        "/products/roses/rose-006/sizes/S/2.webp",
        "/products/roses/rose-006/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-006/sizes/M/1.webp",
        "/products/roses/rose-006/sizes/M/2.webp",
        "/products/roses/rose-006/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-006/sizes/L/1.webp",
        "/products/roses/rose-006/sizes/L/2.webp",
        "/products/roses/rose-006/sizes/L/3.webp"
      ]
    }
  },
  "rose-007": {
    "title": "Грация",
    "folder": "Грация",
    "sizes": {
      "S": [
        "/products/roses/rose-007/sizes/S/1.webp",
        "/products/roses/rose-007/sizes/S/2.webp",
        "/products/roses/rose-007/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-007/sizes/M/1.webp",
        "/products/roses/rose-007/sizes/M/2.webp",
        "/products/roses/rose-007/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-007/sizes/L/1.webp",
        "/products/roses/rose-007/sizes/L/2.webp",
        "/products/roses/rose-007/sizes/L/3.webp"
      ]
    }
  },
  "rose-008": {
    "title": "Джумилия",
    "folder": "Джумилия",
    "sizes": {
      "S": [
        "/products/roses/rose-008/sizes/S/1.webp",
        "/products/roses/rose-008/sizes/S/2.webp",
        "/products/roses/rose-008/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-008/sizes/M/1.webp",
        "/products/roses/rose-008/sizes/M/2.webp",
        "/products/roses/rose-008/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-008/sizes/L/1.webp",
        "/products/roses/rose-008/sizes/L/2.webp",
        "/products/roses/rose-008/sizes/L/3.webp"
      ]
    }
  },
  "rose-009": {
    "title": "Испана",
    "folder": "Испана",
    "sizes": {
      "S": [
        "/products/roses/rose-009/sizes/S/1.webp",
        "/products/roses/rose-009/sizes/S/2.webp",
        "/products/roses/rose-009/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-009/sizes/M/1.webp",
        "/products/roses/rose-009/sizes/M/2.webp",
        "/products/roses/rose-009/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-009/sizes/L/1.webp",
        "/products/roses/rose-009/sizes/L/2.webp",
        "/products/roses/rose-009/sizes/L/3.webp"
      ]
    }
  },
  "rose-010": {
    "title": "Кимберли",
    "folder": "Кимберли",
    "sizes": {
      "S": [
        "/products/roses/rose-010/sizes/S/1.webp",
        "/products/roses/rose-010/sizes/S/2.webp",
        "/products/roses/rose-010/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-010/sizes/M/1.webp",
        "/products/roses/rose-010/sizes/M/2.webp",
        "/products/roses/rose-010/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-010/sizes/L/1.webp",
        "/products/roses/rose-010/sizes/L/2.webp",
        "/products/roses/rose-010/sizes/L/3.webp"
      ]
    }
  },
  "rose-011": {
    "title": "Кинг бабблс",
    "folder": "Кинг бабблс",
    "sizes": {
      "S": [
        "/products/roses/rose-011/sizes/S/1.webp",
        "/products/roses/rose-011/sizes/S/2.webp",
        "/products/roses/rose-011/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-011/sizes/M/1.webp",
        "/products/roses/rose-011/sizes/M/2.webp",
        "/products/roses/rose-011/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-011/sizes/L/1.webp",
        "/products/roses/rose-011/sizes/L/2.webp",
        "/products/roses/rose-011/sizes/L/3.webp"
      ]
    }
  },
  "rose-013": {
    "title": "Лавандер бабблс",
    "folder": "Лавандер бабблс",
    "sizes": {
      "S": [
        "/products/roses/rose-013/sizes/S/1.webp",
        "/products/roses/rose-013/sizes/S/2.webp",
        "/products/roses/rose-013/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-013/sizes/M/1.webp",
        "/products/roses/rose-013/sizes/M/2.webp",
        "/products/roses/rose-013/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-013/sizes/L/1.webp",
        "/products/roses/rose-013/sizes/L/2.webp",
        "/products/roses/rose-013/sizes/L/3.webp"
      ]
    }
  },
  "rose-014": {
    "title": "Лавли Лидия",
    "folder": "Лавли Лидия",
    "sizes": {
      "S": [
        "/products/roses/rose-014/sizes/S/1.webp",
        "/products/roses/rose-014/sizes/S/2.webp",
        "/products/roses/rose-014/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-014/sizes/M/1.webp",
        "/products/roses/rose-014/sizes/M/2.webp",
        "/products/roses/rose-014/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-014/sizes/L/1.webp",
        "/products/roses/rose-014/sizes/L/2.webp",
        "/products/roses/rose-014/sizes/L/3.webp"
      ]
    }
  },
  "rose-015": {
    "title": "Леди бомбастик",
    "folder": "Леди бомбастик",
    "sizes": {
      "S": [
        "/products/roses/rose-015/sizes/S/1.webp",
        "/products/roses/rose-015/sizes/S/2.webp",
        "/products/roses/rose-015/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-015/sizes/M/1.webp",
        "/products/roses/rose-015/sizes/M/2.webp",
        "/products/roses/rose-015/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-015/sizes/L/1.webp",
        "/products/roses/rose-015/sizes/L/2.webp",
        "/products/roses/rose-015/sizes/L/3.webp"
      ]
    }
  },
  "rose-016": {
    "title": "Лидия",
    "folder": "Лидия",
    "sizes": {
      "S": [
        "/products/roses/rose-016/sizes/S/1.webp",
        "/products/roses/rose-016/sizes/S/2.webp",
        "/products/roses/rose-016/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-016/sizes/M/1.webp",
        "/products/roses/rose-016/sizes/M/2.webp",
        "/products/roses/rose-016/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-016/sizes/L/1.webp",
        "/products/roses/rose-016/sizes/L/2.webp",
        "/products/roses/rose-016/sizes/L/3.webp"
      ]
    }
  },
  "rose-017": {
    "title": "Лондон Таймс",
    "folder": "Лондон Таймс",
    "sizes": {
      "S": [
        "/products/roses/rose-017/sizes/S/1.webp",
        "/products/roses/rose-017/sizes/S/2.webp",
        "/products/roses/rose-017/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-017/sizes/M/1.webp",
        "/products/roses/rose-017/sizes/M/2.webp",
        "/products/roses/rose-017/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-017/sizes/L/1.webp",
        "/products/roses/rose-017/sizes/L/2.webp",
        "/products/roses/rose-017/sizes/L/3.webp"
      ]
    }
  },
  "rose-018": {
    "title": "Марвелос бабблс",
    "folder": "Марвелос бабблс",
    "sizes": {
      "S": [
        "/products/roses/rose-018/sizes/S/1.webp",
        "/products/roses/rose-018/sizes/S/2.webp",
        "/products/roses/rose-018/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-018/sizes/M/1.webp",
        "/products/roses/rose-018/sizes/M/2.webp",
        "/products/roses/rose-018/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-018/sizes/L/1.webp",
        "/products/roses/rose-018/sizes/L/2.webp",
        "/products/roses/rose-018/sizes/L/3.webp"
      ]
    }
  },
  "rose-019": {
    "title": "Маритим",
    "folder": "Маритим",
    "sizes": {
      "S": [
        "/products/roses/rose-019/sizes/S/1.webp",
        "/products/roses/rose-019/sizes/S/2.webp",
        "/products/roses/rose-019/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-019/sizes/M/1.webp",
        "/products/roses/rose-019/sizes/M/2.webp",
        "/products/roses/rose-019/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-019/sizes/L/1.webp",
        "/products/roses/rose-019/sizes/L/2.webp",
        "/products/roses/rose-019/sizes/L/3.webp"
      ]
    }
  },
  "rose-020": {
    "title": "Мисс Пигги",
    "folder": "Мисс Пигги",
    "sizes": {
      "S": [
        "/products/roses/rose-020/sizes/S/1.webp",
        "/products/roses/rose-020/sizes/S/2.webp",
        "/products/roses/rose-020/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-020/sizes/M/1.webp",
        "/products/roses/rose-020/sizes/M/2.webp",
        "/products/roses/rose-020/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-020/sizes/L/1.webp",
        "/products/roses/rose-020/sizes/L/2.webp",
        "/products/roses/rose-020/sizes/L/3.webp"
      ]
    }
  },
  "rose-021": {
    "title": "Мисти бабблс",
    "folder": "Мисти бабблс",
    "sizes": {
      "S": [
        "/products/roses/rose-021/sizes/S/1.webp",
        "/products/roses/rose-021/sizes/S/2.webp",
        "/products/roses/rose-021/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-021/sizes/M/1.webp",
        "/products/roses/rose-021/sizes/M/2.webp",
        "/products/roses/rose-021/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-021/sizes/L/1.webp",
        "/products/roses/rose-021/sizes/L/2.webp",
        "/products/roses/rose-021/sizes/L/3.webp"
      ]
    }
  },
  "rose-022": {
    "title": "Пакая",
    "folder": "Пакая",
    "sizes": {
      "S": [
        "/products/roses/rose-022/sizes/S/1.webp",
        "/products/roses/rose-022/sizes/S/2.webp",
        "/products/roses/rose-022/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-022/sizes/M/1.webp",
        "/products/roses/rose-022/sizes/M/2.webp",
        "/products/roses/rose-022/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-022/sizes/L/1.webp",
        "/products/roses/rose-022/sizes/L/2.webp",
        "/products/roses/rose-022/sizes/L/3.webp"
      ]
    }
  },
  "rose-023": {
    "title": "Пени Лейн",
    "folder": "Пени Лейн",
    "sizes": {
      "S": [
        "/products/roses/rose-023/sizes/S/1.webp",
        "/products/roses/rose-023/sizes/S/2.webp",
        "/products/roses/rose-023/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-023/sizes/M/1.webp",
        "/products/roses/rose-023/sizes/M/2.webp",
        "/products/roses/rose-023/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-023/sizes/L/1.webp",
        "/products/roses/rose-023/sizes/L/2.webp",
        "/products/roses/rose-023/sizes/L/3.webp"
      ]
    }
  },
  "rose-024": {
    "title": "Пинк Аваланж",
    "folder": "Пинк Аваланж",
    "sizes": {
      "S": [
        "/products/roses/rose-024/sizes/S/1.webp",
        "/products/roses/rose-024/sizes/S/2.webp",
        "/products/roses/rose-024/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-024/sizes/M/1.webp",
        "/products/roses/rose-024/sizes/M/2.webp",
        "/products/roses/rose-024/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-024/sizes/L/1.webp",
        "/products/roses/rose-024/sizes/L/2.webp",
        "/products/roses/rose-024/sizes/L/3.webp"
      ]
    }
  },
  "rose-025": {
    "title": "Пинк дименшн",
    "folder": "Пинк дименшн",
    "sizes": {
      "S": [
        "/products/roses/rose-025/sizes/S/1.webp",
        "/products/roses/rose-025/sizes/S/2.webp",
        "/products/roses/rose-025/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-025/sizes/M/1.webp",
        "/products/roses/rose-025/sizes/M/2.webp",
        "/products/roses/rose-025/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-025/sizes/L/1.webp",
        "/products/roses/rose-025/sizes/L/2.webp",
        "/products/roses/rose-025/sizes/L/3.webp"
      ]
    }
  },
  "rose-026": {
    "title": "Пинк Флойд",
    "folder": "Пинк Флойд",
    "sizes": {
      "S": [
        "/products/roses/rose-026/sizes/S/1.webp",
        "/products/roses/rose-026/sizes/S/2.webp",
        "/products/roses/rose-026/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-026/sizes/M/1.webp",
        "/products/roses/rose-026/sizes/M/2.webp",
        "/products/roses/rose-026/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-026/sizes/L/1.webp",
        "/products/roses/rose-026/sizes/L/2.webp",
        "/products/roses/rose-026/sizes/L/3.webp"
      ]
    }
  },
  "rose-027": {
    "title": "Пиони бабблс",
    "folder": "Пиони бабблс",
    "sizes": {
      "S": [
        "/products/roses/rose-027/sizes/S/1.webp",
        "/products/roses/rose-027/sizes/S/2.webp",
        "/products/roses/rose-027/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-027/sizes/M/1.webp",
        "/products/roses/rose-027/sizes/M/2.webp",
        "/products/roses/rose-027/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-027/sizes/L/1.webp",
        "/products/roses/rose-027/sizes/L/2.webp",
        "/products/roses/rose-027/sizes/L/3.webp"
      ]
    }
  },
  "rose-028": {
    "title": "Питер Парк",
    "folder": "Питер Парк",
    "sizes": {
      "S": [
        "/products/roses/rose-028/sizes/S/1.webp",
        "/products/roses/rose-028/sizes/S/2.webp",
        "/products/roses/rose-028/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-028/sizes/M/1.webp",
        "/products/roses/rose-028/sizes/M/2.webp",
        "/products/roses/rose-028/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-028/sizes/L/1.webp",
        "/products/roses/rose-028/sizes/L/2.webp",
        "/products/roses/rose-028/sizes/L/3.webp"
      ]
    }
  },
  "rose-029": {
    "title": "Пич Аваланж",
    "folder": "Пич Аваланж",
    "sizes": {
      "S": [
        "/products/roses/rose-029/sizes/S/1.webp",
        "/products/roses/rose-029/sizes/S/2.webp",
        "/products/roses/rose-029/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-029/sizes/M/1.webp",
        "/products/roses/rose-029/sizes/M/2.webp",
        "/products/roses/rose-029/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-029/sizes/L/1.webp",
        "/products/roses/rose-029/sizes/L/2.webp",
        "/products/roses/rose-029/sizes/L/3.webp"
      ]
    }
  },
  "rose-030": {
    "title": "Пич дименшн",
    "folder": "Пич дименшн",
    "sizes": {
      "S": [
        "/products/roses/rose-030/sizes/S/1.webp",
        "/products/roses/rose-030/sizes/S/2.webp",
        "/products/roses/rose-030/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-030/sizes/M/1.webp",
        "/products/roses/rose-030/sizes/M/2.webp",
        "/products/roses/rose-030/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-030/sizes/L/1.webp",
        "/products/roses/rose-030/sizes/L/2.webp",
        "/products/roses/rose-030/sizes/L/3.webp"
      ]
    }
  },
  "rose-031": {
    "title": "Ред Наоми",
    "folder": "Ред Наоми",
    "sizes": {
      "S": [
        "/products/roses/rose-031/sizes/S/1.webp",
        "/products/roses/rose-031/sizes/S/2.webp",
        "/products/roses/rose-031/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-031/sizes/M/1.webp",
        "/products/roses/rose-031/sizes/M/2.webp",
        "/products/roses/rose-031/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-031/sizes/L/1.webp",
        "/products/roses/rose-031/sizes/L/2.webp",
        "/products/roses/rose-031/sizes/L/3.webp"
      ]
    }
  },
  "rose-032": {
    "title": "Ридженс Парк",
    "folder": "Ридженс Парк",
    "sizes": {
      "S": [
        "/products/roses/rose-032/sizes/S/1.webp",
        "/products/roses/rose-032/sizes/S/2.webp",
        "/products/roses/rose-032/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-032/sizes/M/1.webp",
        "/products/roses/rose-032/sizes/M/2.webp",
        "/products/roses/rose-032/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-032/sizes/L/1.webp",
        "/products/roses/rose-032/sizes/L/2.webp",
        "/products/roses/rose-032/sizes/L/3.webp"
      ]
    }
  },
  "rose-033": {
    "title": "Свит Ревайвл",
    "folder": "Свит Ревайвл",
    "sizes": {
      "S": [
        "/products/roses/rose-033/sizes/S/1.webp",
        "/products/roses/rose-033/sizes/S/2.webp",
        "/products/roses/rose-033/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-033/sizes/M/1.webp",
        "/products/roses/rose-033/sizes/M/2.webp",
        "/products/roses/rose-033/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-033/sizes/L/1.webp",
        "/products/roses/rose-033/sizes/L/2.webp",
        "/products/roses/rose-033/sizes/L/3.webp"
      ]
    }
  },
  "rose-034": {
    "title": "Скайвард",
    "folder": "Скайвард",
    "sizes": {
      "S": [
        "/products/roses/rose-034/sizes/S/1.webp",
        "/products/roses/rose-034/sizes/S/2.webp",
        "/products/roses/rose-034/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-034/sizes/M/1.webp",
        "/products/roses/rose-034/sizes/M/2.webp",
        "/products/roses/rose-034/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-034/sizes/L/1.webp",
        "/products/roses/rose-034/sizes/L/2.webp",
        "/products/roses/rose-034/sizes/L/3.webp"
      ]
    }
  },
  "rose-035": {
    "title": "Скарлет дименшн",
    "folder": "Скарлет дименшн",
    "sizes": {
      "S": [
        "/products/roses/rose-035/sizes/S/1.webp",
        "/products/roses/rose-035/sizes/S/2.webp",
        "/products/roses/rose-035/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-035/sizes/M/1.webp",
        "/products/roses/rose-035/sizes/M/2.webp",
        "/products/roses/rose-035/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-035/sizes/L/1.webp",
        "/products/roses/rose-035/sizes/L/2.webp",
        "/products/roses/rose-035/sizes/L/3.webp"
      ]
    }
  },
  "rose-036": {
    "title": "Софи Лорен",
    "folder": "Софи Лорен",
    "sizes": {
      "S": [
        "/products/roses/rose-036/sizes/S/1.webp",
        "/products/roses/rose-036/sizes/S/2.webp",
        "/products/roses/rose-036/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-036/sizes/M/1.webp",
        "/products/roses/rose-036/sizes/M/2.webp",
        "/products/roses/rose-036/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-036/sizes/L/1.webp",
        "/products/roses/rose-036/sizes/L/2.webp",
        "/products/roses/rose-036/sizes/L/3.webp"
      ]
    }
  },
  "rose-037": {
    "title": "Спешл дименшн",
    "folder": "Спешл дименшн",
    "sizes": {
      "S": [
        "/products/roses/rose-037/sizes/S/1.webp",
        "/products/roses/rose-037/sizes/S/2.webp",
        "/products/roses/rose-037/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-037/sizes/M/1.webp",
        "/products/roses/rose-037/sizes/M/2.webp",
        "/products/roses/rose-037/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-037/sizes/L/1.webp",
        "/products/roses/rose-037/sizes/L/2.webp",
        "/products/roses/rose-037/sizes/L/3.webp"
      ]
    }
  },
  "rose-038": {
    "title": "Шангрила",
    "folder": "Шангрила",
    "sizes": {
      "S": [
        "/products/roses/rose-038/sizes/S/1.webp",
        "/products/roses/rose-038/sizes/S/2.webp",
        "/products/roses/rose-038/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-038/sizes/M/1.webp",
        "/products/roses/rose-038/sizes/M/2.webp",
        "/products/roses/rose-038/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-038/sizes/L/1.webp",
        "/products/roses/rose-038/sizes/L/2.webp",
        "/products/roses/rose-038/sizes/L/3.webp"
      ]
    }
  },
  "rose-039": {
    "title": "Эва Ред",
    "folder": "Эва Ред",
    "sizes": {
      "S": [
        "/products/roses/rose-039/sizes/S/1.webp",
        "/products/roses/rose-039/sizes/S/2.webp",
        "/products/roses/rose-039/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-039/sizes/M/1.webp",
        "/products/roses/rose-039/sizes/M/2.webp",
        "/products/roses/rose-039/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-039/sizes/L/1.webp",
        "/products/roses/rose-039/sizes/L/2.webp",
        "/products/roses/rose-039/sizes/L/3.webp"
      ]
    }
  },
  "rose-040": {
    "title": "Эль Торо",
    "folder": "Эль Торо",
    "sizes": {
      "S": [
        "/products/roses/rose-040/sizes/S/1.webp",
        "/products/roses/rose-040/sizes/S/2.webp",
        "/products/roses/rose-040/sizes/S/3.webp"
      ],
      "M": [
        "/products/roses/rose-040/sizes/M/1.webp",
        "/products/roses/rose-040/sizes/M/2.webp",
        "/products/roses/rose-040/sizes/M/3.webp"
      ],
      "L": [
        "/products/roses/rose-040/sizes/L/1.webp",
        "/products/roses/rose-040/sizes/L/2.webp",
        "/products/roses/rose-040/sizes/L/3.webp"
      ]
    }
  }
};

export interface ConstructorFlowerAsset {
  id: string;
  name: string;
  image: string;
  images: string[];
}

export const generatedConstructorFlowers: ConstructorFlowerAsset[] = [
  {
    "id": "constructor-rose-001",
    "name": "Аваланж Белая",
    "image": "/products/constructor/avalanzh-belaya/1.webp",
    "images": [
      "/products/constructor/avalanzh-belaya/1.webp"
    ]
  },
  {
    "id": "constructor-rose-002",
    "name": "Аква",
    "image": "/products/constructor/akva/1.webp",
    "images": [
      "/products/constructor/akva/1.webp"
    ]
  },
  {
    "id": "constructor-rose-003",
    "name": "Барбодос",
    "image": "/products/constructor/barbodos/1.webp",
    "images": [
      "/products/constructor/barbodos/1.webp"
    ]
  },
  {
    "id": "constructor-rose-004",
    "name": "Баттеркап",
    "image": "/products/constructor/batterkap/1.webp",
    "images": [
      "/products/constructor/batterkap/1.webp"
    ]
  },
  {
    "id": "constructor-rose-005",
    "name": "Вайт Барбодос",
    "image": "/products/constructor/vayt-barbodos/1.webp",
    "images": [
      "/products/constructor/vayt-barbodos/1.webp"
    ]
  },
  {
    "id": "constructor-rose-006",
    "name": "Вау",
    "image": "/products/constructor/vau/1.webp",
    "images": [
      "/products/constructor/vau/1.webp"
    ]
  },
  {
    "id": "constructor-rose-007",
    "name": "Грация",
    "image": "/products/constructor/gratsiya/1.webp",
    "images": [
      "/products/constructor/gratsiya/1.webp",
      "/products/constructor/gratsiya/2.webp"
    ]
  },
  {
    "id": "constructor-rose-008",
    "name": "Джумилия",
    "image": "/products/constructor/dzhumiliya/1.webp",
    "images": [
      "/products/constructor/dzhumiliya/1.webp"
    ]
  },
  {
    "id": "constructor-rose-009",
    "name": "Испана",
    "image": "/products/constructor/ispana/1.webp",
    "images": [
      "/products/constructor/ispana/1.webp",
      "/products/constructor/ispana/2.webp"
    ]
  },
  {
    "id": "constructor-rose-010",
    "name": "Кимберли",
    "image": "/products/constructor/kimberli/1.webp",
    "images": [
      "/products/constructor/kimberli/1.webp"
    ]
  },
  {
    "id": "constructor-rose-011",
    "name": "Кинг бабблс",
    "image": "/products/constructor/king-babbls/1.webp",
    "images": [
      "/products/constructor/king-babbls/1.webp",
      "/products/constructor/king-babbls/2.webp"
    ]
  },
  {
    "id": "constructor-rose-013",
    "name": "Лавандер бабблс",
    "image": "/products/constructor/lavander-babbls/1.webp",
    "images": [
      "/products/constructor/lavander-babbls/1.webp"
    ]
  },
  {
    "id": "constructor-rose-014",
    "name": "Лавли Лидия",
    "image": "/products/constructor/lavli-lidiya/1.webp",
    "images": [
      "/products/constructor/lavli-lidiya/1.webp"
    ]
  },
  {
    "id": "constructor-rose-015",
    "name": "Леди бомбастик",
    "image": "/products/constructor/ledi-bombastik/1.webp",
    "images": [
      "/products/constructor/ledi-bombastik/1.webp",
      "/products/constructor/ledi-bombastik/2.webp"
    ]
  },
  {
    "id": "constructor-rose-016",
    "name": "Лидия",
    "image": "/products/constructor/lidiya/1.webp",
    "images": [
      "/products/constructor/lidiya/1.webp"
    ]
  },
  {
    "id": "constructor-rose-017",
    "name": "Лондон Таймс",
    "image": "/products/constructor/london-tayms/1.webp",
    "images": [
      "/products/constructor/london-tayms/1.webp",
      "/products/constructor/london-tayms/2.webp"
    ]
  },
  {
    "id": "constructor-rose-018",
    "name": "Марвелос бабблс",
    "image": "/products/constructor/marvelos-babbls/1.webp",
    "images": [
      "/products/constructor/marvelos-babbls/1.webp",
      "/products/constructor/marvelos-babbls/2.webp"
    ]
  },
  {
    "id": "constructor-rose-019",
    "name": "Маритим",
    "image": "/products/constructor/maritim/1.webp",
    "images": [
      "/products/constructor/maritim/1.webp",
      "/products/constructor/maritim/2.webp",
      "/products/constructor/maritim/3.webp"
    ]
  },
  {
    "id": "constructor-rose-020",
    "name": "Мисс Пигги",
    "image": "/products/constructor/miss-piggi/1.webp",
    "images": [
      "/products/constructor/miss-piggi/1.webp"
    ]
  },
  {
    "id": "constructor-rose-021",
    "name": "Мисти бабблс",
    "image": "/products/constructor/misti-babbls/1.webp",
    "images": [
      "/products/constructor/misti-babbls/1.webp",
      "/products/constructor/misti-babbls/2.webp"
    ]
  },
  {
    "id": "constructor-rose-022",
    "name": "Пакая",
    "image": "/products/constructor/pakaya/1.webp",
    "images": [
      "/products/constructor/pakaya/1.webp"
    ]
  },
  {
    "id": "constructor-rose-023",
    "name": "Пени Лейн",
    "image": "/products/constructor/peni-leyn/1.webp",
    "images": [
      "/products/constructor/peni-leyn/1.webp"
    ]
  },
  {
    "id": "constructor-rose-024",
    "name": "Пинк Аваланж",
    "image": "/products/constructor/pink-avalanzh/1.webp",
    "images": [
      "/products/constructor/pink-avalanzh/1.webp",
      "/products/constructor/pink-avalanzh/2.webp"
    ]
  },
  {
    "id": "constructor-rose-025",
    "name": "Пинк дименшн",
    "image": "/products/constructor/pink-dimenshn/1.webp",
    "images": [
      "/products/constructor/pink-dimenshn/1.webp",
      "/products/constructor/pink-dimenshn/2.webp"
    ]
  },
  {
    "id": "constructor-rose-026",
    "name": "Пинк Флойд",
    "image": "/products/constructor/pink-floyd/1.webp",
    "images": [
      "/products/constructor/pink-floyd/1.webp",
      "/products/constructor/pink-floyd/2.webp"
    ]
  },
  {
    "id": "constructor-rose-027",
    "name": "Пиони бабблс",
    "image": "/products/constructor/pioni-babbls/1.webp",
    "images": [
      "/products/constructor/pioni-babbls/1.webp",
      "/products/constructor/pioni-babbls/2.webp"
    ]
  },
  {
    "id": "constructor-rose-028",
    "name": "Питер Парк",
    "image": "/products/constructor/piter-park/1.webp",
    "images": [
      "/products/constructor/piter-park/1.webp",
      "/products/constructor/piter-park/2.webp"
    ]
  },
  {
    "id": "constructor-rose-029",
    "name": "Пич Аваланж",
    "image": "/products/constructor/pich-avalanzh/1.webp",
    "images": [
      "/products/constructor/pich-avalanzh/1.webp",
      "/products/constructor/pich-avalanzh/2.webp"
    ]
  },
  {
    "id": "constructor-rose-030",
    "name": "Пич дименшн",
    "image": "/products/constructor/pich-dimenshn/1.webp",
    "images": [
      "/products/constructor/pich-dimenshn/1.webp",
      "/products/constructor/pich-dimenshn/2.webp"
    ]
  },
  {
    "id": "constructor-rose-031",
    "name": "Ред Наоми",
    "image": "/products/constructor/red-naomi/1.webp",
    "images": [
      "/products/constructor/red-naomi/1.webp",
      "/products/constructor/red-naomi/2.webp"
    ]
  },
  {
    "id": "constructor-rose-032",
    "name": "Ридженс Парк",
    "image": "/products/constructor/ridzhens-park/1.webp",
    "images": [
      "/products/constructor/ridzhens-park/1.webp"
    ]
  },
  {
    "id": "constructor-rose-033",
    "name": "Свит Ревайвл",
    "image": "/products/constructor/svit-revayvl/1.webp",
    "images": [
      "/products/constructor/svit-revayvl/1.webp"
    ]
  },
  {
    "id": "constructor-rose-034",
    "name": "Скайвард",
    "image": "/products/constructor/skayvard/1.webp",
    "images": [
      "/products/constructor/skayvard/1.webp",
      "/products/constructor/skayvard/2.webp"
    ]
  },
  {
    "id": "constructor-rose-035",
    "name": "Скарлет дименшн",
    "image": "/products/constructor/skarlet-dimenshn/1.webp",
    "images": [
      "/products/constructor/skarlet-dimenshn/1.webp"
    ]
  },
  {
    "id": "constructor-rose-036",
    "name": "Софи Лорен",
    "image": "/products/constructor/sofi-loren/1.webp",
    "images": [
      "/products/constructor/sofi-loren/1.webp",
      "/products/constructor/sofi-loren/2.webp"
    ]
  },
  {
    "id": "constructor-rose-037",
    "name": "Спешл дименшн",
    "image": "/products/constructor/speshl-dimenshn/1.webp",
    "images": [
      "/products/constructor/speshl-dimenshn/1.webp"
    ]
  },
  {
    "id": "constructor-rose-038",
    "name": "Шангрила",
    "image": "/products/constructor/shangrila/1.webp",
    "images": [
      "/products/constructor/shangrila/1.webp"
    ]
  },
  {
    "id": "constructor-rose-039",
    "name": "Эва Ред",
    "image": "/products/constructor/eva-red/1.webp",
    "images": [
      "/products/constructor/eva-red/1.webp"
    ]
  },
  {
    "id": "constructor-rose-040",
    "name": "Эль Торо",
    "image": "/products/constructor/el-toro/1.webp",
    "images": [
      "/products/constructor/el-toro/1.webp",
      "/products/constructor/el-toro/2.webp"
    ]
  }
];
